version: '3.5'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb-vol:/var/lib/mysql
    networks:
      - Inception
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress-vol:/var/www/wordpress
    networks:
      - Inception
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress-vol:/var/www/wordpress
    networks:
      - Inception
    restart: always
    ports:
      - 443:443
    depends_on:
      - wordpress

networks:
  Inception:
    name: Inception

volumes:

  mariadb-vol:
    name: mariadb-volume
    driver_opts:
      device: /home/jrinna/data/mariadb
      type: volume
      o: bind

  wordpress-vol:
    name: wordpress-volume
    driver_opts:
      device: /home/jrinna/data/wordpress
      type: volume
      o: bind
