version: '3.5'

services:
        mariadb:
                container_name: mariadb
                build: ./requirements/mariadb
                networks:
                        - inception
                volumes:
                        - mariadb_volume:/var/lib/mysql
                restart: on-failure
                env_file:
                        - .env

        wordpress:
                container_name: wordpress
                build: ./requirements/wordpress
                networks:
                        - inception
                depends_on:
                        - mariadb
                volumes:
                        - wordpress_volume:/var/www/wordpress
                restart: on-failure
                env_file:
                        - .env

        nginx:
                container_name: nginx
                build: ./requirements/nginx
                networks:
                        - inception
                depends_on:
                        - wordpress
                volumes:
                        - wordpress_volume:/var/www/wordpress
                restart: on-failure
                ports:
                        - "443:443"

networks:
        inception:
                name: inception

volumes:
        mariadb_volume:
                name: mariadb_volume
                driver_opts:
                        device: /home/rgarcia/data/mariadb
                        type: 'none'
                        o: bind
        
        wordpress_volume:
               name: wordpress_volume
               driver_opts:
                       device: /home/rgarcia/data/mariadb
                       type: 'none'
                       o: bind
